---
name: install and configure my developer machine, complete set-up with everything I need
- hosts: localhost
  become: true
# Action/Tasks Declaration
tasks:
  - name: istall package mc
    apt: name=mc state=latest

