---
- name: "Playing with Ansible and Git"
  hosts: localhost
  become: true # This means that all tasks will be executed with sudo
  connection: local

  vars:
   home: /home/razvan
   intellij_home: /opt/intellij

  tasks:
    - name: "install apt package mc"
      apt:
        name: mc
        state: latest

    - name: "install apt package HTOP"
      apt: name=htop state=latest

    - name: crate a directory for intellij location
      become: yes
      file:
        path: "{{intellij_home}}"
        state: directory

    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      unarchive:
        src: https://download.jetbrains.com/idea/ideaIU-2020.3.1.tar.gz
        dest: "{{intellij_home}}/"
        remote_src: yes