---
- name: "Playing with Ansible and Git"
  hosts: localhost
  become: true # This means that all tasks will be executed with sudo
  connection: local

  vars:
   home: /home/razvan

  tasks:
    - name: "install apt package mc"
      apt:
        name: mc
        state: latest

    - name: "install apt package HTOP"
      apt: name=htop state=latest

    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      unarchive:
        src: https://download.jetbrains.com/idea/ideaIE-2020.3.tar.gz
        dest: "{{home}}/Downloads"
        remote_src: yes